name: burcmania
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  build_runner: ^2.3.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  lottie: ^2.2.0
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/json/
    - assets/svg/
    - assets/language/
